version: 2
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: jekyll/builder:4.1.0
        user: root
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c1:44:43:84:15:0b:5b:af:05:2d:52:fa:81:32:8d:f3"
      - checkout
      - run:
          name: List files
          command: ls -la
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Build static site
          command: bundle exec jekyll build --destination /tmp/blog
      - run:
          name: Deploy to GitHub pages
          command: |
            git checkout master
            git pull --rebase origin master
            cp -r /tmp/blog/* $(pwd)
            git config user.email "gabrielweyer@gmail.com"
            git config user.name "Gabriel Weyer"
            git add .
            git commit -m "Release"
            git push origin master
test:
  override:
    - "true"
