version: 2
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: jekyll/builder:4.1.0
        user: jekyll
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c4:76:8a:90:8c:a5:d4:3c:c1:56:fd:a5:4e:88:63:44"
      - checkout
      - run:
          name: Install Gems
          command: bundle install
      - run:
          name: Build static site
          command: bundle exec jekyll build --destination /tmp/blog
      - run:
          name: Deploy to GitHub pages
          command: |
            git checkout master
            git pull --rebase origin master
            cp -r /tmp/blog/* $(pwd)
            git config user.email "gabrielweyer@gmail.com"
            git config user.name "Gabriel Weyer"
            git add .
            git commit -m "Release"
            git push origin master
test:
  override:
    - "true"
