version: 2
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: jekyll/builder:4.1.0
        user: jekyll
    steps:
      - add_ssh_keys:
          fingerprints:
            - "06:b5:54:2a:ce:49:a1:2a:c6:1d:0c:3f:e1:d7:6e:15"
      - checkout
      - run:
          name: Install Gems
          command: |
            bundle config set --local path 'vendor/bundle'
            bundle install
      - run:
          name: Build static site
          command: bundle exec jekyll build --destination /tmp/blog
      - run:
          name: Deploy to GitHub pages
          command: |
            git checkout master
            git pull --rebase origin master
            cp -r /tmp/blog/* $(pwd)
            git config user.email "gabrielweyer@gmail.com"
            git config user.name "Gabriel Weyer"
            git add .
            git commit -m "Release"
            git push origin master
test:
  override:
    - "true"
